/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Car {
  'id' : string,
  'model' : string,
  'mileage' : bigint,
  'imageUrls' : Array<string>,
  'make' : string,
  'year' : bigint,
  'description' : string,
  'price' : bigint,
}
export interface CarInput {
  'model' : string,
  'mileage' : bigint,
  'imageUrls' : Array<string>,
  'make' : string,
  'year' : bigint,
  'description' : string,
  'price' : bigint,
}
export interface Inquiry {
  'id' : string,
  'status' : string,
  'buyerEmail' : string,
  'carId' : string,
  'createdAt' : bigint,
  'buyerPhone' : string,
  'message' : string,
  'buyerName' : string,
}
export interface Order {
  'buyerEmail' : string,
  'orderStatus' : string,
  'carId' : string,
  'createdAt' : bigint,
  'buyerPhone' : string,
  'orderId' : string,
  'updatedAt' : bigint,
  'buyerName' : string,
  'paymentAmount' : bigint,
}
export interface OrderInput {
  'buyerEmail' : string,
  'carId' : string,
  'buyerPhone' : string,
  'buyerName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCar' : ActorMethod<[CarInput], Car>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCar' : ActorMethod<[string], boolean>,
  'deleteInquiry' : ActorMethod<[string], boolean>,
  'deleteOrder' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCar' : ActorMethod<[string], [] | [Car]>,
  'getCars' : ActorMethod<[], Array<Car>>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getOrderById' : ActorMethod<[string], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'submitOrder' : ActorMethod<
    [OrderInput],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateCar' : ActorMethod<[string, CarInput], boolean>,
  'updateInquiryStatus' : ActorMethod<[string, string], boolean>,
  'updateOrderStatus' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];