/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CarInput = IDL.Record({
  'model' : IDL.Text,
  'mileage' : IDL.Nat,
  'imageUrls' : IDL.Vec(IDL.Text),
  'make' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const Car = IDL.Record({
  'id' : IDL.Text,
  'model' : IDL.Text,
  'mileage' : IDL.Nat,
  'imageUrls' : IDL.Vec(IDL.Text),
  'make' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'buyerEmail' : IDL.Text,
  'carId' : IDL.Text,
  'createdAt' : IDL.Int,
  'buyerPhone' : IDL.Text,
  'message' : IDL.Text,
  'buyerName' : IDL.Text,
});
export const Order = IDL.Record({
  'buyerEmail' : IDL.Text,
  'orderStatus' : IDL.Text,
  'carId' : IDL.Text,
  'createdAt' : IDL.Int,
  'buyerPhone' : IDL.Text,
  'orderId' : IDL.Text,
  'updatedAt' : IDL.Int,
  'buyerName' : IDL.Text,
  'paymentAmount' : IDL.Nat,
});
export const OrderInput = IDL.Record({
  'buyerEmail' : IDL.Text,
  'carId' : IDL.Text,
  'buyerPhone' : IDL.Text,
  'buyerName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCar' : IDL.Func([CarInput], [Car], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCar' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteInquiry' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteOrder' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCar' : IDL.Func([IDL.Text], [IDL.Opt(Car)], ['query']),
  'getCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getOrderById' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitOrder' : IDL.Func(
      [OrderInput],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateCar' : IDL.Func([IDL.Text, CarInput], [IDL.Bool], []),
  'updateInquiryStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateOrderStatus' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CarInput = IDL.Record({
    'model' : IDL.Text,
    'mileage' : IDL.Nat,
    'imageUrls' : IDL.Vec(IDL.Text),
    'make' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Car = IDL.Record({
    'id' : IDL.Text,
    'model' : IDL.Text,
    'mileage' : IDL.Nat,
    'imageUrls' : IDL.Vec(IDL.Text),
    'make' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'buyerEmail' : IDL.Text,
    'carId' : IDL.Text,
    'createdAt' : IDL.Int,
    'buyerPhone' : IDL.Text,
    'message' : IDL.Text,
    'buyerName' : IDL.Text,
  });
  const Order = IDL.Record({
    'buyerEmail' : IDL.Text,
    'orderStatus' : IDL.Text,
    'carId' : IDL.Text,
    'createdAt' : IDL.Int,
    'buyerPhone' : IDL.Text,
    'orderId' : IDL.Text,
    'updatedAt' : IDL.Int,
    'buyerName' : IDL.Text,
    'paymentAmount' : IDL.Nat,
  });
  const OrderInput = IDL.Record({
    'buyerEmail' : IDL.Text,
    'carId' : IDL.Text,
    'buyerPhone' : IDL.Text,
    'buyerName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCar' : IDL.Func([CarInput], [Car], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCar' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteInquiry' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteOrder' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCar' : IDL.Func([IDL.Text], [IDL.Opt(Car)], ['query']),
    'getCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getOrderById' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitOrder' : IDL.Func(
        [OrderInput],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateCar' : IDL.Func([IDL.Text, CarInput], [IDL.Bool], []),
    'updateInquiryStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateOrderStatus' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };